import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import react from "@astrojs/react";
import node from "@astrojs/node";
import fs from "node:fs";
import remarkPythonRefs from "./src/plugins/remark-python-refs";

const isDev = process.env.NODE_ENV === "development" || process.argv.includes("dev");

// Load redirects generated by the migration script
// Astro prepends `base` to the redirect source but not the target,
// so we prepend it ourselves for non-root deployments.
const base = isDev ? "" : "/python-insider-blog";
let redirects: Record<string, string> = {};
try {
  const redirectsPath = new URL("./src/data/redirects.json", import.meta.url);
  const raw: Record<string, string> = JSON.parse(fs.readFileSync(redirectsPath, "utf-8"));
  for (const [from, to] of Object.entries(raw)) {
    redirects[from] = `${base}${to}`;
  }
} catch {
  // No redirects file yet (run migration first)
}

// Keystatic integration only in dev mode (requires server rendering)
const integrations = [mdx(), sitemap(), react()];
if (isDev) {
  const keystatic = (await import("@keystatic/astro")).default;
  integrations.push(keystatic());
}

// When moving to blog.python.org, change site and remove base:
//   site: "https://blog.python.org",
//   base: "/",
export default defineConfig({
  site: "https://jacobcoffee.github.io",
  base: isDev ? "/" : "/python-insider-blog",
  integrations,
  output: isDev ? "server" : "static",
  ...(isDev && {
    adapter: node({ mode: "standalone" }),
  }),
  markdown: {
    remarkPlugins: [remarkPythonRefs],
  },
  redirects,
});
