import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import react from "@astrojs/react";
import node from "@astrojs/node";
import fs from "node:fs";
import remarkPythonRefs from "./src/plugins/remark-python-refs";

const isDev = process.env.NODE_ENV === "development" || process.argv.includes("dev");

// Load redirects generated by the migration script
let redirects: Record<string, string> = {};
try {
  const redirectsPath = new URL("./src/data/redirects.json", import.meta.url);
  redirects = JSON.parse(fs.readFileSync(redirectsPath, "utf-8"));
} catch {
  // No redirects file yet (run migration first)
}

// Blogger feed URL → new RSS feed
redirects["/feeds/posts/default"] = "/rss.xml";

// Keystatic integration only in dev mode (requires server rendering)
const integrations = [mdx(), sitemap(), react()];
if (isDev) {
  const keystatic = (await import("@keystatic/astro")).default;
  integrations.push(keystatic());
}

export default defineConfig({
  site: "https://blog.python.org",
  base: "/",
  integrations,
  output: isDev ? "server" : "static",
  ...(isDev && {
    adapter: node({ mode: "standalone" }),
  }),
  markdown: {
    remarkPlugins: [remarkPythonRefs],
  },
  redirects,
});
